name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa

      - name: Add server to known hosts
        run: ssh-keyscan ${{ secrets.SERVER_IP }} >> $HOME/.ssh/known_hosts

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: $HOME/.ssh/id_rsa
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/154.56.46.133/fastapi-production-1
            ./deploy.sh
