name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh        

      - name: Add server to known hosts
        run: ssh-keyscan ${{ secrets.SERVER_IP }} >> $HOME/.ssh/known_hosts

      - name: executing remote ssh commands using ssh key
        uses: ./
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: /var/www/154.56.46.133/fastapi-production-1/deploy.sh
